from __future__ import annotations

import os
from pathlib import PurePath
from typing import Optional

from app.analysis.models import RiskLevel, StorageCategory


# Known file extensions for media and documents
MEDIA_EXTENSIONS = frozenset({
    # Images
    ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp",
    ".heic", ".heif", ".svg", ".raw", ".cr2", ".nef", ".arw", ".psd",
    # Video
    ".mov", ".mp4", ".m4v", ".mkv", ".avi", ".wmv", ".flv", ".webm",
    ".mpg", ".mpeg", ".3gp",
    # Audio
    ".mp3", ".wav", ".aac", ".flac", ".m4a", ".ogg", ".aiff", ".wma",
})

DOCUMENT_EXTENSIONS = frozenset({
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".txt", ".rtf", ".pages", ".numbers", ".key", ".csv", ".tsv",
    ".odt", ".ods", ".odp", ".md", ".tex", ".epub",
})

LOG_EXTENSIONS = frozenset({
    ".log", ".crash", ".diag", ".ips", ".asl", ".out",
})

DEVELOPER_DIR_NAMES = frozenset({
    "node_modules",
    ".venv",
    "venv",
    "virtualenv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    "htmlcov",
    ".coverage",
    "DerivedData",
    ".cargo",
    ".gradle",
    ".m2",
    ".nuget",
    ".pub-cache",
    ".git",
    ".svn",
    ".hg",
})


def classify_path(
    path: str,
    item_type: Optional[str] = None,
) -> tuple[StorageCategory, RiskLevel, float, str, str]:
    """
    Deterministically classify a filesystem path into a category and risk level.

    Returns a tuple of:
        (category, risk_level, confidence, reason, recommendation)

    Safety Requirement:
        Recommendations NEVER state that a file is 'safe to delete'.
        All language remains strictly conservative and advisory.
    """
    normalized_path = os.path.normpath(path)
    pure_path = PurePath(normalized_path)
    parts = pure_path.parts
    parts_lower = [p.lower() for p in parts]
    filename = pure_path.name.lower()
    suffix = pure_path.suffix.lower()

    # 1. Check for Xcode and Developer paths
    if "deriveddata" in parts_lower or "xcode" in parts_lower and ("deriveddata" in parts_lower or "archives" in parts_lower):
        return (
            StorageCategory.DEVELOPMENT,
            RiskLevel.MEDIUM,
            0.95,
            "Detected Xcode build artifacts / DerivedData location.",
            "Developer build cache. Review before cleanup; artifacts can usually be regenerated by rebuilding projects in Xcode.",
        )

    # 2. Check for Docker storage
    if any(p in parts_lower for p in ["com.docker.docker", "docker.raw", "docker.qcow2"]):
        return (
            StorageCategory.DEVELOPMENT,
            RiskLevel.MEDIUM,
            0.90,
            "Detected Docker container or virtual disk storage.",
            "Docker storage artifact. Review active Docker containers and volumes before considering cleanup.",
        )

    # 3. Check for specific developer directory names in path parts
    for part in parts:
        if part in DEVELOPER_DIR_NAMES or part.lower() in DEVELOPER_DIR_NAMES:
            return (
                StorageCategory.DEVELOPMENT,
                RiskLevel.MEDIUM,
                0.90,
                f"Path contains standard development artifact or dependency folder: '{part}'.",
                "Developer dependencies or build artifacts. Review before removal; dependencies can typically be re-installed using package managers.",
            )

    # 4. Check for Cache paths
    if "caches" in parts_lower or "cache" in parts_lower or ".cache" in parts_lower or "_cacache" in parts_lower:
        # Check if it's within ~/Library/Caches
        if any("library" == parts_lower[i] and "caches" == parts_lower[i + 1] for i in range(len(parts_lower) - 1)):
            return (
                StorageCategory.CACHE,
                RiskLevel.LOW,
                0.95,
                "Located within macOS user or system Caches directory (Library/Caches).",
                "Review this cache directory before cleanup. Caches are often rebuilt by parent applications as needed.",
            )
        return (
            StorageCategory.CACHE,
            RiskLevel.LOW,
            0.85,
            "Path contains a recognized cache directory name.",
            "Review this cache location before cleanup. Verify that associated applications are inactive.",
        )

    # 5. Check for Log paths and log file extensions
    if suffix in LOG_EXTENSIONS or filename.endswith(".log.gz") or filename.endswith(".log.1"):
        return (
            StorageCategory.LOGS,
            RiskLevel.LOW,
            0.90,
            f"File has a recognized log file extension ('{suffix}').",
            "Review historical log files before considering cleanup. Verify whether recent logs are needed for troubleshooting.",
        )

    if any(p in ("logs", "log") for p in parts_lower) or any("library" == parts_lower[i] and "logs" == parts_lower[i + 1] for i in range(len(parts_lower) - 1)):
        return (
            StorageCategory.LOGS,
            RiskLevel.LOW,
            0.90,
            "Path is located within a standard system or application logs directory.",
            "Review historical log files before considering cleanup. Older logs can often be archived or pruned if no longer needed.",
        )

    # 6. Check for Application Data / Support paths
    if any("application support" in p for p in parts_lower) or any("library" == parts_lower[i] and "application support" == parts_lower[i + 1] for i in range(len(parts_lower) - 1)):
        return (
            StorageCategory.APPLICATION_DATA,
            RiskLevel.HIGH,
            0.95,
            "Located within macOS Application Support directory.",
            "Application support data. Contains active configuration, local databases, or user state; manual review required.",
        )

    if any("containers" in p or "group containers" in p for p in parts_lower):
        return (
            StorageCategory.APPLICATION_DATA,
            RiskLevel.HIGH,
            0.90,
            "Located within sandboxed macOS Container or Group Container directory.",
            "Application container storage. May contain application sandbox state or user data; manual review required.",
        )

    # 7. Check for Media files
    if suffix in MEDIA_EXTENSIONS:
        return (
            StorageCategory.MEDIA,
            RiskLevel.HIGH,
            0.90,
            f"File matches known media format extension ('{suffix}').",
            "User media asset. Do not remove unless verified as redundant or disposable by the user.",
        )

    # 8. Check for Documents
    if suffix in DOCUMENT_EXTENSIONS:
        return (
            StorageCategory.DOCUMENTS,
            RiskLevel.HIGH,
            0.90,
            f"File matches known document format extension ('{suffix}').",
            "User document. Retain file; manual user inspection required.",
        )

    # 9. Fallback: Unknown
    return (
        StorageCategory.UNKNOWN,
        RiskLevel.UNKNOWN,
        0.0,
        "Unclassified filesystem item. Path does not match any recognized rule.",
        "Manual review recommended. Unknown item type; no automatic cleanup recommendation can be provided.",
    )
