"""
MacGuard AI Phase 12 — Storage Investigation & Evidence Models.

Defines structured evidence representations, usage & dependency indicators,
reclaimability confidence tiers, progressive investigation levels, and cleanup plans.

CORE INVARIANTS:
1. DISCOVERY != CATEGORIZATION != AUTHORIZATION
2. Deterministic evidence is 100% authoritative over storage numbers and safety boundaries.
3. Ollama may reason over structured evidence but has zero filesystem mutation authority.
4. Dependency and active-usage signals are optional/unknown when not reliably detectable.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field

from app.models.category import ConfidenceLevel, SmartCategory
from app.models.risk import RiskLevel


def format_bytes(size_bytes: int) -> str:
    """Format bytes as human-readable string (binary / decimal standard)."""
    if size_bytes < 0:
        return "0 B"
    for unit in ["B", "KB", "MB", "GB", "TB"]:
        if size_bytes < 1024.0:
            return f"{size_bytes:.2f} {unit}" if unit != "B" else f"{size_bytes} B"
        size_bytes /= 1024.0
    return f"{size_bytes:.2f} PB"


class InvestigationLevel(str, Enum):
    """Progressive investigation depth levels."""

    HEALTH = "HEALTH"          # Level 1: Fast physical disk metrics & health check
    TARGETED = "TARGETED"      # Level 2: High-value user-controlled areas (caches, developer, AI, Docker, logs)
    DEEP = "DEEP"              # Level 3: Comprehensive structured traversal across allowed scope
    SPECIFIC = "SPECIFIC"      # Level 4: Focused investigation of a single category or path


class ReclaimConfidence(str, Enum):
    """
    Confidence tiers for potential storage reclamation.
    Combines deterministic category risk, path safety, and runtime dependency signals.
    """

    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"      # Safe caches, temporary build caches, discarded disk images
    REVIEW_REQUIRED = "REVIEW_REQUIRED"      # Active venvs, docker data, developer repos, large downloads
    LOW_CONFIDENCE = "LOW_CONFIDENCE"        # Unclassified user data, ambiguous caches, shared resources
    PROTECTED = "PROTECTED"                  # System files, active applications, OS-managed containers


class StorageEvidenceItem(BaseModel):
    """
    Structured, deterministic evidence for a single storage finding or consumer group.
    """

    model_config = ConfigDict(frozen=True, validate_assignment=True)

    evidence_id: str = Field(..., description="Deterministic unique identifier (e.g. 'ev_cache_001')")
    path: str = Field(..., description="Path to the discovered storage item or directory")
    canonical_path: str = Field(..., description="Canonical resolved path without symlinks or firmlink aliases")
    size_bytes: int = Field(..., ge=0, description="Size in bytes")
    item_count: int = Field(default=1, ge=0, description="Number of files/items inside if directory")

    category: SmartCategory = Field(..., description="Semantic category")
    subcategory: str = Field(default="general", description="Granular subcategory (e.g. 'uv_cache', 'xcode_derived_data')")
    source_app: Optional[str] = Field(default=None, description="Originating application if identifiable")
    likely_owner: Optional[str] = Field(default=None, description="User, system, or tool owner")
    filesystem_type: Optional[str] = Field(default=None, description="APFS volume/filesystem type if known")

    # Semantic flags
    is_cache: bool = Field(default=False, description="Whether this is temporary cache data")
    is_generated: bool = Field(default=False, description="Whether this data was generated by a tool/build")
    is_developer: bool = Field(default=False, description="Whether this relates to software development")
    is_ai_ml: bool = Field(default=False, description="Whether this relates to AI/ML models/datasets")
    is_docker: bool = Field(default=False, description="Whether this relates to Docker containers/images/volumes")
    is_duplicate: bool = Field(default=False, description="Whether this item is a verified duplicate")
    is_system_managed: bool = Field(default=False, description="Whether this path is protected/system-managed")

    # Safety & Reclaimability
    risk_level: RiskLevel = Field(..., description="Deterministic risk classification (LOW, MEDIUM, HIGH, UNKNOWN)")
    reclaim_confidence: ReclaimConfidence = Field(..., description="Reclaimability confidence tier")
    cleanup_allowed: bool = Field(default=False, description="Whether deterministic rules permit human review for cleanup")
    reason_if_not_allowed: Optional[str] = Field(default=None, description="Explanation if cleanup is blocked")

    # Runtime Usage & Dependency Signals (None = UNKNOWN/Undetermined)
    currently_in_use: Optional[bool] = Field(default=None, description="Whether an active open file handle/lock is detected")
    associated_processes: list[str] = Field(default_factory=list, description="Names of running processes associated with this item")
    associated_application_running: Optional[bool] = Field(default=None, description="Whether the parent application is currently running")
    active_dependency_detected: Optional[bool] = Field(default=None, description="Whether another active project/tool references this path")
    referenced_by_active_project: Optional[bool] = Field(default=None, description="Whether an active workspace references this path")
    mounted_or_active: Optional[bool] = Field(default=None, description="Whether item is part of an active mount or runtime container")
    recently_modified: Optional[bool] = Field(default=None, description="Whether modified within recent threshold (e.g. 7 days)")
    reproducible_or_redownloadable: Optional[bool] = Field(default=None, description="Whether contents can be re-downloaded or re-built")
    dependency_evidence: Optional[str] = Field(default=None, description="Deterministic evidence detailing dependencies")
    usage_evidence: Optional[str] = Field(default=None, description="Deterministic evidence detailing process/file activity")
    cleanup_consequence: Optional[str] = Field(default=None, description="Likely consequence if removed (e.g. 'Must re-download models on next run')")

    evidence_notes: str = Field(default="", description="Descriptive rationale for this evidence item")

    @property
    def size_human(self) -> str:
        return format_bytes(self.size_bytes)


class StorageInvestigationEvidence(BaseModel):
    """
    Aggregated, verified storage evidence for a completed investigation run.
    Contains strictly deterministic totals, category distributions, and individual evidence items.
    """

    model_config = ConfigDict(frozen=True, validate_assignment=True)

    investigation_id: str = Field(..., description="Unique run identifier")
    level: InvestigationLevel = Field(..., description="Investigation depth level")
    target_path: str = Field(..., description="Target root investigated")

    # Physical Disk Accounting
    disk_total_bytes: int = Field(..., ge=0, description="Total physical disk size")
    disk_used_bytes: int = Field(..., ge=0, description="Physical disk space in use")
    disk_free_bytes: int = Field(..., ge=0, description="Physical free disk space available")

    # macOS Storage Semantics
    macos_system_data_reported_bytes: Optional[int] = Field(
        default=None,
        description="macOS-reported System Data figure if supplied (not claimed to equal analyzed total)",
    )

    # Deterministic Analyzed Metrics
    analyzed_bytes: int = Field(..., ge=0, description="Total user-accessible bytes inspected by MacGuard")
    candidate_inventory_bytes: int = Field(..., ge=0, description="Total bytes across all flagged candidate items")
    eligible_for_review_bytes: int = Field(..., ge=0, description="Bytes passing deterministic safety allowlist for review")

    # Reclaimability Breakdown (Deterministic)
    reclaimable_high_confidence_bytes: int = Field(..., ge=0, description="High confidence reclaimable bytes (safe caches, temp)")
    reclaimable_review_required_bytes: int = Field(..., ge=0, description="Review required bytes (docker, venvs, repos, downloads)")
    reclaimable_low_confidence_bytes: int = Field(default=0, ge=0, description="Low confidence / ambiguous bytes")
    protected_bytes: int = Field(..., ge=0, description="Protected / system-managed storage bytes inspected")

    items: list[StorageEvidenceItem] = Field(default_factory=list, description="All discovered evidence items")
    category_summaries: dict[str, int] = Field(default_factory=dict, description="Bytes per SmartCategory name")
    top_consumers: list[StorageEvidenceItem] = Field(default_factory=list, description="Largest storage consumers ranked descending")

    @property
    def total_reclaimable_bytes(self) -> int:
        """Sum of high-confidence and review-required reclaimable storage."""
        return self.reclaimable_high_confidence_bytes + self.reclaimable_review_required_bytes

    @property
    def disk_total_human(self) -> str:
        return format_bytes(self.disk_total_bytes)

    @property
    def disk_used_human(self) -> str:
        return format_bytes(self.disk_used_bytes)

    @property
    def disk_free_human(self) -> str:
        return format_bytes(self.disk_free_bytes)

    @property
    def analyzed_human(self) -> str:
        return format_bytes(self.analyzed_bytes)

    @property
    def total_reclaimable_human(self) -> str:
        return format_bytes(self.total_reclaimable_bytes)


class CleanupPlanItem(BaseModel):
    """A single actionable item in a validated CleanupPlan."""

    model_config = ConfigDict(frozen=True, validate_assignment=True)

    evidence_id: str = Field(..., description="Reference to the deterministic StorageEvidenceItem")
    path: str = Field(..., description="Path to item")
    canonical_path: str = Field(..., description="Canonical path")
    size_bytes: int = Field(..., ge=0)
    category: SmartCategory
    subcategory: str
    tier: ReclaimConfidence
    requires_review: bool = Field(default=True)
    description: str = Field(default="")
    consequence: Optional[str] = Field(default=None)

    @property
    def size_human(self) -> str:
        return format_bytes(self.size_bytes)


class CleanupPlan(BaseModel):
    """
    Deterministic cleanup plan derived from validated investigation findings.
    """

    model_config = ConfigDict(frozen=True, validate_assignment=True)

    high_confidence_items: list[CleanupPlanItem] = Field(default_factory=list)
    review_required_items: list[CleanupPlanItem] = Field(default_factory=list)
    protected_items: list[CleanupPlanItem] = Field(default_factory=list)

    total_reclaimable_bytes: int = Field(default=0, ge=0)
    high_confidence_bytes: int = Field(default=0, ge=0)
    review_required_bytes: int = Field(default=0, ge=0)

    @property
    def total_reclaimable_human(self) -> str:
        return format_bytes(self.total_reclaimable_bytes)

    @property
    def high_confidence_human(self) -> str:
        return format_bytes(self.high_confidence_bytes)

    @property
    def review_required_human(self) -> str:
        return format_bytes(self.review_required_bytes)


class LLMReasonedFinding(BaseModel):
    """
    An LLM-reasoned finding that strictly references a deterministic evidence_id.
    """

    model_config = ConfigDict(frozen=True, validate_assignment=True)

    evidence_id: str = Field(..., description="Must match an existing deterministic evidence_id")
    why_it_exists: str = Field(default="", description="LLM explanation of what created this data")
    why_safe_or_unsafe: str = Field(default="", description="LLM explanation of safety / dependencies")
    consequence: str = Field(default="", description="What happens if reclaimed")
    recommended_priority: int = Field(default=999, ge=1, description="Recommended investigation/cleanup order (1=highest)")


class StorageInvestigationResult(BaseModel):
    """
    Final investigation report combining deterministic evidence with optional local AI reasoning.
    """

    model_config = ConfigDict(frozen=True, validate_assignment=True)

    evidence: StorageInvestigationEvidence
    cleanup_plan: CleanupPlan

    summary_text: str = Field(..., description="Executive overview of storage health and findings")
    severity: str = Field(default="INFO", description="CRITICAL, WARNING, or HEALTHY")
    reasoning_notes: list[str] = Field(default_factory=list, description="Categorized reasoning or guidance bullets")
    llm_findings: list[LLMReasonedFinding] = Field(default_factory=list, description="Reasoned findings from Ollama if available")

    is_ai_reasoned: bool = Field(default=False, description="True if Ollama reasoned over evidence; False if deterministic fallback")
    ai_status_message: Optional[str] = Field(default=None, description="Details on local AI availability or fallback reason")
