from __future__ import annotations

from typing import Optional
from pydantic import BaseModel, ConfigDict, Field

from app.analysis.models import RiskLevel, StorageCandidate, StorageCategory
from app.analysis.recommendations import RecommendationAction, StorageRecommendation


class FindingSummary(BaseModel):
    """Structured summary of an individual storage finding."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    path: str = Field(..., min_length=1, description="Canonical path of the item.")
    size_formatted: str = Field(..., description="Human-readable size.")
    category: str = Field(..., description="Deterministic category name.")
    risk_level: str = Field(..., description="Deterministic risk level.")
    action: str = Field(..., description="Advisory recommendation action.")
    explanation: str = Field(..., min_length=1, description="Explanation of why this item was flagged.")


class AnalysisContext(BaseModel):
    """
    Deterministic context prepared for the LLM.

    Contains only passive analysis and recommendation facts.
    MUST NEVER contain approval secret keys, tokens, or environment credentials.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    scan_id: str = Field(..., min_length=1, description="Unique scan session identifier.")
    scan_path: str = Field(..., min_length=1, description="Target root path of the scan.")
    total_scanned_items: int = Field(..., ge=0, description="Total number of items evaluated.")
    total_size_bytes: int = Field(..., ge=0, description="Total size in bytes of scanned items.")
    candidates: list[StorageCandidate] = Field(
        default_factory=list,
        description="List of classified storage candidates.",
    )
    recommendations: list[StorageRecommendation] = Field(
        default_factory=list,
        description="List of deterministic storage recommendations.",
    )
    safety_summary: dict[str, int] = Field(
        default_factory=dict,
        description="Counts of items per risk level or safety status.",
    )


class LLMExplanation(BaseModel):
    """
    Structured response generated by the LLM explanation layer.

    This model is strictly explanatory and contains no executable commands.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    summary: str = Field(
        ...,
        min_length=1,
        description="Executive summary of the storage findings.",
    )
    key_findings: list[FindingSummary] = Field(
        default_factory=list,
        description="Structured key storage consumers identified in the scan.",
    )
    prioritized_findings: list[str] = Field(
        default_factory=list,
        description="Ordered list of findings prioritized by size, risk, and impact.",
    )
    user_guidance: str = Field(
        ...,
        min_length=1,
        description="Non-destructive guidance reminding the user to review findings.",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Safety warnings regarding protected or high-risk locations.",
    )
